#!/bin/bash

# Close STDERR
#exec 2<&-

TENANT_ID=$(keystone token-get 2>/dev/null |  awk '/ tenant_id / {print $4;}')
OS_TENANT_ID=${OS_TENANT_ID:-$TENANT_ID}

IMG_ID=$(nova image-list | grep "Apache"  | grep "2.6.0" | awk 'NR==1 {print $2}')
IMAGE_ID=${IMAGE_ID:-$IMG_ID}

PUB1_NET=$(nova net-list | awk '/ public / {print $2; exit}')
PUB2_NET=$(nova net-list | awk '/ internet / {print $2; exit}')
PUBLIC_NET=${PUBLIC_NET:-${PUB1_NET:-$PUB2_NET}}

PRI_NET=$(nova net-list | awk '!/(+|ID|public|internet)/ {print $2; exit}')
PRIVATE_NET=${PRIVATE_NET:-$PRI_NET}

KEY_ID=$(nova keypair-list | awk '!/(+|Name)/ {print $2; exit}')
KEYPAIR_ID=${KEYPAIR:-$KEY_ID}
echo KEYPAIR_ID=$KEYPAIR_ID

FLAVOR_ID=${FLAVOR_ID:-23}
echo FLAVOR_ID=$FLAVOR_ID

if [ $SAHARA_URL ]; then
  sa="sahara --insecure --bypass-url $SAHARA_URL/v1.1/$OS_TENANT_ID"
else
  sa="sahara --insecure"
fi


sed "s/_flavorid/$FLAVOR_ID/" v260/v260master > v260/v260master_temp
sed -i "s/_public_net/$PUBLIC_NET/" v260/v260master_temp
masterid=`$sa node-group-template-create --json v260/v260master_temp | awk '/ id / {print \$4}'`
if [ -z $master1id ]; then
  masterid=`$sa node-group-template-list | awk '/v260master/ {print $4; exit;}'`
fi
echo v260master ID: $master1id

sed "s/_flavorid/$FLAVOR_ID/" v260/v260worker > v260/v260worker_temp
sed -i "s/_public_net/$PUBLIC_NET/" v260/v260worker_temp
workerid=`$sa node-group-template-create --json v260/v260worker_temp | awk '/ id / {print $4}'`
if [ -z $workerid ]; then
  workerid=`$sa node-group-template-list | awk '/v260worker/ {print $4; exit;}'`
fi
echo v260worker ID: $workerid

sed "s/_masterid/$masterid/" v260/v260cluster > v260/v260cluster_temp
sed -i "s/_workerid/$workerid/" v260/v260cluster_temp
clusterid=`$sa cluster-template-create --json v260/v260cluster_temp | awk '/ id / {print $4}'`
clusterid=`$sa cluster-template-create --json v260/v260cluster_temp | awk '/ id / {print $4}'`
if [ -z $clusterid ]; then
  clusterid=`$sa cluster-template-list | awk '/v260 / {print $4; exit;}'`
fi
echo cluster ID: $clusterid

# Redirect STDERR to STDOUT
exec 2>&1

sed "s/_clusterid/$clusterid/" v260/v260launch > v260/v260launch_temp
sed -i "s/_imageid/$IMAGE_ID/" v260/v260launch_temp
sed -i "s/_private_net/$PRIVATE_NET/" v260/v260launch_temp
sed -i "s/_keypairid/$KEYPAIR_ID/" v260/v260launch_temp

$sa cluster-create --json v260/v260launch_temp
 
